### ISSUE TITLE
Gateron的腳位有問題

### ISSUE THREAD

**Issue by DreaM117er** [siderakb/key-switches.pretty#1]
SW_Gateron_LowProfile_HotSwap_THT，這個腳位需要做水平翻轉的動作，不然做出來的板子會有問題。

先前參照這個腳位做出來的單格電路板就有這個狀況，大大再修正一下。

**Comment by ziteh** [comment]
非常感謝您的回報，這個 footprint 確實畫反了，我會修正。

**Comment by ziteh** [comment]
已於 8bccda5 修正，[Ver 0.8.0](https://github.com/siderakb/key-switches.pretty/releases/tag/v0.8.0) 發佈。
